# Generated by Django 4.1.7 on 2024-04-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=60.0),
        ),
    ]
