# Generated by Django 4.1.7 on 2024-04-18 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cakes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('text', models.CharField(max_length=255)),
                ('checked', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, default='recipe_avatars/no-photo.png', null=True, upload_to='recipe_avatars/')),
                ('likes', models.IntegerField(default=0)),
                ('total_proteins', models.FloatField()),
                ('total_fats', models.FloatField()),
                ('total_carbohydrates', models.FloatField()),
                ('total_calories', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liked', models.ManyToManyField(related_name='liked_users', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(to='cakes.product')),
                ('steps', models.ManyToManyField(to='diary.step')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField()),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('calories', models.IntegerField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cakes.product')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diary.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_proteins', models.FloatField()),
                ('total_fats', models.FloatField()),
                ('total_carbohydrates', models.FloatField()),
                ('total_calories', models.IntegerField()),
                ('water', models.FloatField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('breakfast', models.ManyToManyField(related_name='breakfast_set', to='diary.meal')),
                ('dinner', models.ManyToManyField(related_name='dinner_set', to='diary.meal')),
                ('lunch', models.ManyToManyField(related_name='lunch_set', to='diary.meal')),
                ('snack', models.ManyToManyField(related_name='snack_set', to='diary.meal')),
            ],
        ),
    ]
